inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'tmp/**/*'

# Lint
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*_component.rb'

Lint/UselessAccessModifier:
  Exclude:
    - 'test/test_helper.rb'

# Layout
Layout/LineLength:
  Exclude:
    - 'test/**/*_test.rb'

# Style
Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/**/*.rb'
    - 'config/application.rb'
    - 'db/migrate/*.rb'
    - 'lib/**/*.rb'
    - 'test/**/*_test.rb'
    - 'test/*_helper.rb'
    - 'test/application_system_test_case.rb'

Style/RedundantFetchBlock:
  Enabled: true
  Exclude:
    - 'config/puma.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/components/**/*_component.rb'
    - 'app/helpers/**/*_helper.rb'
    - 'test/**/*_test.rb'
    - 'test/channels/application_cable/connection_test.rb'
    - 'test/test_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config.ru'
    - 'config/**/*'
