# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.7.4'

gem 'rails', '~> 6.1'
gem 'tzinfo-data'
gem 'view_component'

# Drivers
gem 'pg'

gem 'puma', '~> 5.6'

# JavaScript, CSS and assets
gem 'cssbundling-rails'
gem 'jbuilder'
gem 'jsbundling-rails'
gem 'stimulus-rails'
gem 'turbolinks', '~> 5'

# Logging
gem 'scout_apm'

# Profiling/troubleshooting
gem 'flamegraph'
gem 'rack-mini-profiler'
gem 'rbtrace'
gem 'stackprof'

# Other
gem 'aws-sdk-s3', require: false
gem 'better_html'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'grover'
gem 'serviceworker-rails'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # Code critics
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'erb_lint', '~> 0.1', require: false
  gem 'rubocop', '~> 1.19', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'webdrivers'
end
