# frozen_string_literal: true

source 'https://rubygems.org'

ruby '4.0.2'

gem 'rails', '~> 7.2.0'
gem 'tzinfo-data'
gem 'view_component'

# Drivers
gem 'pg'

gem 'puma', '~> 7.0', '>= 7.0.4'

# JavaScript, CSS and assets
gem 'cssbundling-rails'
gem 'propshaft'
gem 'benchmark'
gem 'bigdecimal'
gem 'drb'
gem 'jbuilder'
gem 'jsbundling-rails'
gem 'logger'
gem 'mutex_m'
gem 'ostruct'
gem 'stimulus-rails'
gem 'tsort', '>= 0.2'

# Logging
gem 'scout_apm', '~> 6.1.0'

# Profiling/troubleshooting
gem 'flamegraph'
gem 'rack-mini-profiler'
gem 'rbtrace'
gem 'stackprof'

# Other
gem 'aws-sdk-s3', require: false
gem 'better_html'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'grover'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  # Code critics
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'erb_lint', '~> 0.1', require: false
  gem 'rubocop', '~> 1.19', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
end

group :development do
  gem 'listen', '~> 3.8'
  gem 'web-console'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'minitest', '~> 5.27'
  gem 'selenium-webdriver'
end
