source 'https://rubygems.org'

gem 'jekyll'
gem 'github-pages', group: :jekyll_plugins
gem 'github-pages-unscramble', group: :jekyll_plugins
gem 'benchmark'
gem 'logger'
gem 'csv'
gem 'base64'
gem 'bigdecimal'
gem 'ostruct'

gem 'rubocop'
