// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import CircuitSvgController from "./circuit_svg_controller.ts"
application.register("circuit-svg", CircuitSvgController)

import ClipboardController from "./clipboard_controller.ts"
application.register("clipboard", ClipboardController)

import ShareController from "./share_controller.ts"
application.register("share", ShareController)
